algoritmo "Olá, Mundo!"
var
    // Declaração da variável msg do tipo caractere
    msg: caractere
inicio
    // Atribuição de valor à variável msg.
    msg <- "Olá, Mundo!" 
    escreval(msg) // Exibe o valor da variável msg na tela.
    escreva("Me livrei da maldição do 'Olá, Mundo!'") // Exibe uma mensagem adicional na tela.
fimalgoritmo

// Essa é uma maneira de fazer usando variáveis, para armazenar a mensagem, "Olá, Mundo!".