algoritmo "Soma"
var
    n1, n2, s: inteiro
inicio
    
    escreva("Digite um valor: ")
    leia(n1)
    escreva("Digite outro valor: ")
    leia(n2)
    s <- n1 + n2
    escreva("A soma entre ", n1," e ", 5," é igual a ", s ,".")
fimalgoritmo
// 4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório 
// entre eles. 
// Ex: 
// Digite um valor: 8 
// Digite outro valor: 5 
// A soma entre 8 e 5 é igual a 13.