algoritmo "Dolar_Creuza"
var
    dolar, cotacao, reais: real
inicio
    escreva("Qunatos reais eu tenho? ")
    leia(reais)
    escreva("Qual a cotação do dólar? ")
    leia(cotacao)
    dolar <- reais / cotacao
    escreva("Posso ter U$",dolar:2:2)    
fimalgoritmo
// Situação 02
// Creuza vai viajar e precisa comprar dólares, ela quer saber quanto vai pagar em reais
// para isso ela vai perguntar a cotação do dólar e quantos dólares ela vai comprar.
