algoritmo "Equ_Segundo_Grau"
var
    a, b, c: real
inicio
    escreva("Informe o valor de A: ")
    leia(a)
    escreva("Informe o valor de B: ")
    leia(b)
    escreva("Informe o valor de C: ")
    leia(c)
    
    escreva("Valor de Delta: ",(b ^ 2 - 4 * a * c))
fimalgoritmo

// Calculando o valor de ddelta na saída de dados.

// 11) Desenvolva uma lógica que leia os valores de A, B e C de uma equação do 
// segundo grau e mostre o valor de Delta.

// Correção: Certo.