algoritmo "Dobro"
var
    n, dobro, terca_part: real
inicio
    escreva("Informe um valor: ")
    leia(n)
    dobro <- n * 2
    terca_part <- n / 3
    escreval("O dobro de ", n, " é ",dobro)
    escreva("A terça parte de ", n, " é ",terca_part)
fimalgoritmo
// 7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a 
// sua terça parte. 
// Ex:  
// Digite um número: 3.5 
// O dobro de 3.5 é 7.0 
// A terça parte de 3.5 é 1.16666 