algoritmo "Funconário"
var
    dias_trab_mes: inteiro
inicio
    escreva("Informe a quantidade de dias trabalhados no mês: ")
    leia(dias_trab_mes)

    escreval("Salário R$", (8 * 25) * dias_trab_mes)
fimalgoritmo

// Algoritmo feito com o processamento na saída de dados.

// 15) Crie um programa que leia o número de dias trabalhados em um mês e mostre o 
// salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25 
// por hora trabalhada.

// Correção: Certo