algoritmo "Salário"
var
    salario: real
inicio
    escreva("Informe o valor do seu salário: R$")
    leia(salario)

    escreva("Seu novo salário com 15% de aumento R$",(salario + (salario * 15 / 100)))
fimalgoritmo

// Fazendo o calculo na saída de dados.

// 13) Faça um algoritmo que leia o salário de um funcionário, calcule e mostre o 
// seu novo salário, com 15% de aumento.

// Correção: Certo.