 algoritmo "Sucessor_e_Antecessor"
var
    n: inteiro
inicio
    escreva("Informe o valor: ")
    leia(n)

    escreval("O Sucessor de ",n , " e ", n + 1)
    escreva("O Antecessor de ",n , " e ", n - 1)
fimalgoritmo

// Maneira feita, fazendo o calculo na saída de dados.

// 6) Faça um programa que leia um número inteiro e mostre o seu antecessor e seu 
// sucessor. 
// Ex:  
// Digite um número: 9 
// O antecessor de 9 é 8 
// O sucessor de 9 é 10

// Correção: Certo.