algoritmo "Pares_Ímpares"
var
    n, cont: inteiro
inicio
    cont <- 0 // Inicializa o contador com 0
    enquanto cont < 6 faca
        escreva("Digite o ",cont + 1,"° número: ") // Solicita ao usuário um número
        leia(n)
        cont <- cont + 1 // Incrementa o contador


        // Falta terminar o código


    fimenquanto
fimalgoritmo
// 49) Crie um programa que leia 6 números inteiros e no final mostre quantos deles 
// são pares e quantos são ímpares.