algoritmo "Sorteio"
var
    n_sorteado: inteiro
inicio
    //Randi escolhe um número de 0 ate 10, ele descosidera o 11.
    n_sorteado <- randi(11)
    escreva(n_sorteado)



    //Falta terminar de fazer esse programa.




fimalgoritmo
//50) Desenvolva um programa que faça o sorteio de 20 números entre 0 e 10 e 
//mostre na tela: 
 //a) Quais foram os números sorteados 
 //b) Quantos números estão acima de 5 
 //c) Quantos números são divisíveis por 3