algoritmo "Carteira"
var
    carteira, dolar: real
inicio
    escreva("Quanto de Dinheiro você tem na carteira? R$")
    leia(carteira)

    dolar <- carteira / 3.45
    escreva("Você pode comprar ",dolar:2:2, " Dolares.")
fimalgoritmo

// Usando variável para fazer o calculo.

// 9) Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira (em R$) 
// e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$3,45. 

// Correção: Certo.