algoritmo "Carteira"
var
    carteira: real
inicio
    escreva("Quanto de Dinheiro você tem na carteira? R$")
    leia(carteira)

    escreva("Você pode comprar ",carteira / 3.45, " Dolares.")
fimalgoritmo

// Fazendo o calculo na saída de dados.

// 9) Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira (em R$) 
// e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$3,45. 

// Correção: Certo. Obs: Não consegui formatar o número...