algoritmo "Contador de 0 a 10"
var
    // Declarando o contador como inteiro.
    contador: inteiro
inicio
    // Inicializando o contador com 0
    contador <- 0
    // Enquanto o contador for menor ou igual a 10, faça.
    enquanto (contador <= 10) faca
        // Contador tá recebendo o valor do contador + 1.
        escreval (contador)
        contador <- contador + 1 
    fimenquanto
    escreval ("Terminei de contar")
fimalgoritmo